name: meme_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.2.3 # Dart SDK version
  flutter: 3.16.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  drift: ^2.15.0
  provider: ^6.1.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  shimmer: ^3.0.0
  appinio_social_share: ^0.3.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.8
  surf_lint_rules: 3.0.0
flutter:
  uses-material-design: true

  fonts:
    - family: Mefika
      fonts: 
        - asset: assets/fonts/mefika-font/Mefika.ttf

  assets:
    - assets/