name: meme_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.2.3 # Dart SDK version
  flutter: 3.16.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  matrix_gesture_detector: ^0.2.0-nullsafety.1
  text_editor: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true

  assets:
    - assets/noimage.jpg

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf